services:
- docker
script:
- docker build -t api .
- docker tag api $DOCKER_USERNAME/guilhermerenew/api:20200529
- docker push guilhermerenew/api:20200529
after_script:
- docker images
env:
  global:
    secure: YE7Q6TeoqOltnWJd0FskG1QZnDFSNFmbatnAv9Th64K1/XIUdJP6DhpmovyCAvJ/hgyoW9hK+1oTkJ32zasYnd2e65UBtFZQDsN+hkxZ7rPA8tPA3se4/+FdUjcd7/glIRl5GVs+GJ5n6AxOkev6dw4/YQzbeDtFeLgqt4T4Q4E2ulYKNDs1AvprJbF+QM0JGpro63SmZBdyttEB2soGxqWdCmG7Yi+W+0weW5407C6M/uPZs7OfEE8g9UFc6wXzbG47/b6TMrrAuh1BYqyi83ffJqez2xYtg/HuNNa9Lh7RuS1KUsM+1euMvJOxrjLRVHY5ZZEGPrKI/lmOvOwqZ6TxP6kLJ6WpD4QsfjS22skAEZqUA6odMKn5i/E2u8EOc2k+uHVK9pGIKCjvgNBtf7gSO0R1YS5lQv6/V9PAj5G9Qu5CnYfJP4HP70mUY8daCcZtK1rbucH84Zr1jAtTtcl1/jOkxXy57B0/1vd0ck/NyRs7IQ2DGSVtOI+HyF+kDQCR0WmrxZ5BspPNQi2+Nu3SKCbA3dGwhyis3vxdXJD6v7gPk5pfxXgbDYxtqSOyP/QtklH1d5MGDn52x0r/RomSCAre+miuW7k8bADFDaSrWUNZkQpMZQ/YTVMnTNPKHGPu6mZDMcxxqQsgbqFmOopb5GRVGJm5rEFIdI1D/yc=